apiVersion: v1
kind: Pod
metadata:
  name: lxcfs-pod
  namespace: default
  annotations:
    "lxcfs-admission-webhook.caicloud.io/mutate": "yes"
spec:
  containers:
  - command:
    - sh
    - -c
    - echo Hello Kubernetes! && sleep 86400
    image: test.cargo.io/library/centos-debug:v1.0
    imagePullPolicy: IfNotPresent
    name: lxcfs-pod
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "0.5"
        memory: 512Mi

